version: '3'
services:
  bench:
    image: raymondelooff/php-caching-benchmarks
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      data:
        aliases:
          - bench.docker
  redis:
    image: redis:alpine
    networks:
      data:
        aliases:
          - redis.docker
networks:
  data: ~
