version: '3'
services:
  bench:
    image: raymondelooff/php-caching-benchmarks
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - benchmark
  redis:
    image: redis:alpine
    networks:
      - benchmark
networks:
  benchmark: ~
