version: '3'
services:
  bench:
    image: raymondelooff/php-caching-benchmarks
    environment:
      - REDIS_HOST=redis.docker
      - REDIS_PORT=6379
    links:
      - redis
  redis:
    image: "redis:alpine"
    networks:
          data:
            aliases:
              - redis.docker
