version: '3'
services:
  bench:
    image: raymondelooff/php-caching-benchmarks
    environment:
      - REDIS_HOST=benchmark_redis
      - REDIS_PORT=6379
    networks:
      - benchmark_benchmark
  redis:
    image: redis:alpine
    networks:
      - benchmark_benchmark
networks:
  benchmark:
    driver: overlay
